version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    links:
      - consul
    ports:
      - "8080:8080"
  consul:
    command: -server -bootstrap -advertise ${HOST_IP}
    image: progrium/consul
    container_name: consul
    logging:
        driver: json-file
    ports:
      - "8500:8500"
  product:
    image: product:latest
    logging:
       driver: json-file
  images:
    image: images:latest
    logging:
       driver: json-file
  ecommerce:
    image: ecommerce:latest
    logging:
       driver: json-file
